[package]
name = "tekst"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
colored = "2.1.0"
crossterm = "0.27.0"
diff = "0.1.13"
notify-debouncer-mini = "0.4.1"

[lints.clippy]
pedantic = "warn"
